### ISSUE TITLE
Please work on sorting this out

### ISSUE THREAD

**Issue by Ma1hT3ach3r** [jaip777/Intro-to-JavaScript#1]
Hi Jai,

I am glad you are working on getting Git functioning in your workflow and using it to get your projects onto GitHub.

Please to have it so that your sketched are able to be posted on a webpage. The goal is to be able to show what you have done to the world.

Think of it as a resume.

i.e: ensure all pages have their own file, .html and .css file: read [Should .html and .css be in different files?](https://www.codecademy.com/en/forum_questions/53c65bc57c82caeae700207a)

Keep up the good work!

**Comment by jaip777** [comment]
Hi M.O, sorry about that, I hadn't realised that they were all in one file. Just used git bash to pull onto my computer, and added them as separate files.

Thanks!
